<?php
/**
 * Preload Tester class.
 *
 * Generates and manages test files for measuring preload performance.
 *
 * @package OPcache_Preload_Generator
 */

namespace OPcache_Preload_Generator;

// Exit if accessed directly.
if (! defined('ABSPATH')) {
	exit;
}

/**
 * Handles generation and execution of preload test files.
 */
class Preload_Tester {

	/**
	 * Default test file name.
	 *
	 * @var string
	 */
	const TEST_FILE_NAME = 'preloadtest.php';

	/**
	 * Get the test file path.
	 *
	 * @return string
	 */
	public function get_test_file_path(): string {

		return ABSPATH . self::TEST_FILE_NAME;
	}

	/**
	 * Generate the test file.
	 *
	 * @param string $preload_path Path to the preload.php file.
	 * @return true|string True on success, error message on failure.
	 */
	public function generate_test_file(string $preload_path) {

		$test_path            = $this->get_test_file_path();
		$preload_path_escaped = addslashes($preload_path);
		$abspath_escaped      = addslashes(ABSPATH);

		$content = <<<'PHP'
<?php
/**
 * OPcache Preload Test File
 *
 * This file tests the preload configuration by measuring homepage load time.
 * Generated by OPcache Preload Generator.
 *
 * @generated
 */

// Security: Only allow requests with valid test token.
$token_file = '__ABSPATH__' . '.opcache_test_token';
$expected_token = file_exists($token_file) ? trim(file_get_contents($token_file)) : '';
$provided_token = $_GET['token'] ?? '';

if (empty($expected_token) || empty($provided_token) || !hash_equals($expected_token, $provided_token)) {
	http_response_code(403);
	header('Content-Type: application/json');
	echo json_encode([
		'success' => false,
		'error' => 'Invalid or missing test token',
		'code' => 'invalid_token'
	]);
	exit;
}

// Set JSON content type.
header('Content-Type: application/json');

$result = [
	'success' => false,
	'time_ms' => 0,
	'memory_peak' => 0,
	'output_valid' => false,
	'error' => null,
	'code' => null
];

try {
	// Record start state.
	$start_time = hrtime(true);
	$start_memory = memory_get_usage(true);

	// Note: We do NOT include the preload file here.
	// The preload file is designed to be loaded by PHP-FPM at startup, not at runtime.
	// Including it during a request would cause conflicts (e.g., constants already defined).
	// Instead, we rely on the safety analyzer to filter out unsafe files, and this test
	// measures WordPress load time to verify the site still works after adding files.

	// Define ABSPATH if not already defined.
	if (!defined('ABSPATH')) {
		define('ABSPATH', '__ABSPATH__');
	}

	// Start output buffering.
	ob_start();

	// Register shutdown function to catch fatal errors.
	// Fatal errors (E_ERROR, E_PARSE, etc.) cannot be caught by set_error_handler().
	register_shutdown_function(function() use (&$result) {
		$error = error_get_last();
		if ($error !== null && ($error['type'] & (E_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR))) {
			// Clean up output buffer.
			while (ob_get_level() > 0) {
				ob_end_clean();
			}
			header('Content-Type: application/json');
			echo json_encode([
				'success' => false,
				'error' => $error['message'],
				'code' => 'fatal_error',
				'file' => $error['file'],
				'line' => $error['line'],
				'time_ms' => 0,
				'memory_peak' => memory_get_peak_usage(true),
				'output_valid' => false
			], JSON_PRETTY_PRINT);
		}
	});

	// Capture all errors (warnings, notices, etc.).
	$old_error_reporting = error_reporting(E_ALL);
	$captured_errors = [];
	set_error_handler(function($errno, $errstr, $errfile, $errline) use (&$captured_errors) {
		$captured_errors[] = [
			'type' => $errno,
			'message' => $errstr,
			'file' => $errfile,
			'line' => $errline
		];
		return false; // Let normal error handler continue.
	});

	// Include WordPress.
	$wp_load = '__ABSPATH__' . 'wp-load.php';
	if (!file_exists($wp_load)) {
		throw new Exception('wp-load.php not found');
	}

	// Set up minimal request environment.
	$_SERVER['REQUEST_URI'] = '/';
	$_SERVER['REQUEST_METHOD'] = 'GET';
	$_SERVER['HTTP_HOST'] = $_SERVER['HTTP_HOST'] ?? 'localhost';

	// We need to trick WordPress into thinking this is a normal request.
	define('WP_USE_THEMES', true);

	// Include WordPress.
	require $wp_load;

	// Get the homepage.
	// Use the main query to render the homepage.
	if (function_exists('wp')) {
		wp();
	}

	// Include template if available.
	if (function_exists('get_header')) {
		// WordPress is loaded, try to get template.
		$template = get_index_template();
		if ($template) {
			include $template;
		}
	}

	// Capture output.
	$output = ob_get_clean();
	$output_length = strlen($output);

	// Restore error handling.
	restore_error_handler();
	error_reporting($old_error_reporting);

	// Calculate timing.
	$end_time = hrtime(true);
	$duration_ns = $end_time - $start_time;
	$duration_ms = $duration_ns / 1e6;

	// Validate output looks like a homepage.
	$has_html = stripos($output, '<html') !== false || stripos($output, '<!DOCTYPE') !== false;
	$has_body = stripos($output, '<body') !== false;
	$has_head = stripos($output, '<head') !== false;
	$min_length = 1000; // Minimum reasonable homepage size.

	$output_valid = $has_html && $has_body && $has_head && $output_length >= $min_length;

	// Check for significant errors (warnings and above, excluding notices/deprecations).
	$significant_errors = array_filter($captured_errors, function($err) {
		return $err['type'] & (E_WARNING | E_USER_WARNING | E_USER_ERROR | E_RECOVERABLE_ERROR);
	});

	// Build result.
	$has_errors = !empty($significant_errors);
	$result['success'] = $output_valid && !$has_errors;
	$result['time_ms'] = round($duration_ms, 2);
	$result['memory_peak'] = memory_get_peak_usage(true);
	$result['output_valid'] = $output_valid;
	$result['output_length'] = $output_length;
	$result['checks'] = [
		'has_html' => $has_html,
		'has_body' => $has_body,
		'has_head' => $has_head,
		'min_length' => $output_length >= $min_length
	];

	// Include captured errors in result.
	if (!empty($captured_errors)) {
		$result['php_errors'] = $captured_errors;
	}

	if ($has_errors) {
		$first_error = reset($significant_errors);
		$result['error'] = $first_error['message'];
		$result['code'] = 'php_error';
		$result['file'] = $first_error['file'];
		$result['line'] = $first_error['line'];
	} elseif (!$output_valid) {
		$result['error'] = 'Output does not appear to be a valid homepage';
		$result['code'] = 'invalid_output';
	}

} catch (Throwable $e) {
	// Clean up output buffer if still open.
	while (ob_get_level() > 0) {
		ob_end_clean();
	}

	$result['success'] = false;
	$result['error'] = $e->getMessage();
	$result['code'] = 'exception';
	$result['file'] = $e->getFile();
	$result['line'] = $e->getLine();
}

echo json_encode($result, JSON_PRETTY_PRINT);
exit;
PHP;

		// Replace placeholders.
		$content = str_replace('__PRELOAD_PATH__', $preload_path_escaped, $content);
		$content = str_replace('__ABSPATH__', $abspath_escaped, $content);

		// Write the file.
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
		$written = file_put_contents($test_path, $content);

		if (false === $written) {
			return __('Failed to write test file.', 'opcache-preload-generator');
		}

		return true;
	}

	/**
	 * Delete the test file.
	 *
	 * @return bool
	 */
	public function delete_test_file(): bool {

		$test_path = $this->get_test_file_path();

		if (file_exists($test_path)) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return unlink($test_path);
		}

		return true;
	}

	/**
	 * Check if test file exists.
	 *
	 * @return bool
	 */
	public function test_file_exists(): bool {

		return file_exists($this->get_test_file_path());
	}

	/**
	 * Generate a secure test token.
	 *
	 * @return string
	 */
	public function generate_test_token(): string {

		return wp_generate_password(32, false);
	}

	/**
	 * Get the test URL.
	 *
	 * @param string $token Security token.
	 * @return string
	 */
	public function get_test_url(string $token): string {

		return home_url(self::TEST_FILE_NAME . '?token=' . rawurlencode($token));
	}

	/**
	 * Run the test via HTTP request.
	 *
	 * @param string $token Security token.
	 * @return array Test results.
	 */
	public function run_test(string $token): array {

		$url = $this->get_test_url($token);

		// Set the environment variable for the token.
		// This needs to be set in the PHP-FPM or Apache environment.
		// For now, we'll pass it via GET and validate in the test file.

		$response = wp_remote_get(
			$url,
			[
				'timeout'   => 60,
				'sslverify' => false,
			]
		);

		if (is_wp_error($response)) {
			return [
				'success' => false,
				'error'   => $response->get_error_message(),
				'code'    => 'request_failed',
			];
		}

		$body = wp_remote_retrieve_body($response);

		// Extract JSON from response body.
		// WordPress plugins (like Docket Cache) may add HTML comments after our JSON output.
		// Find the JSON object boundaries and extract just the JSON.
		$json_body = $this->extract_json_from_response($body);

		$data = json_decode($json_body, true);

		if (null === $data) {
			return [
				'success' => false,
				'error'   => 'Invalid JSON response from test file',
				'code'    => 'invalid_json',
				'body'    => substr($body, 0, 500),
			];
		}

		return $data;
	}

	/**
	 * Extract JSON object from response body.
	 *
	 * WordPress plugins may add HTML comments or other content after our JSON output.
	 * This method finds and extracts just the JSON object.
	 *
	 * @param string $body Response body.
	 * @return string Extracted JSON string.
	 */
	private function extract_json_from_response(string $body): string {

		// Trim whitespace.
		$body = trim($body);

		// If it starts with {, find the matching closing brace.
		if ('{' === substr($body, 0, 1)) {
			$depth = 0;
			$len   = strlen($body);

			for ($i = 0; $i < $len; $i++) {
				$char = $body[ $i ];

				if ('{' === $char) {
					++$depth;
				} elseif ('}' === $char) {
					--$depth;

					if (0 === $depth) {
						return substr($body, 0, $i + 1);
					}
				}
			}
		}

		// Return original body if we can't extract JSON.
		return $body;
	}
}
