<?php
/**
 * Preload Tester class.
 *
 * Generates and manages test files for measuring preload performance.
 *
 * @package OPcache_Preload_Generator
 */

namespace OPcache_Preload_Generator;

// Exit if accessed directly.
if (! defined('ABSPATH')) {
	exit;
}

/**
 * Handles generation and execution of preload test files.
 */
class Preload_Tester {

	/**
	 * Default test file name.
	 *
	 * @var string
	 */
	const TEST_FILE_NAME = 'preloadtest.php';

	/**
	 * Get the test file path.
	 *
	 * @return string
	 */
	public function get_test_file_path(): string {

		return ABSPATH . self::TEST_FILE_NAME;
	}

	/**
	 * Generate the test file.
	 *
	 * @param string $preload_path Path to the preload.php file.
	 * @return true|string True on success, error message on failure.
	 */
	public function generate_test_file(string $preload_path) {

		$test_path            = $this->get_test_file_path();
		$preload_path_escaped = addslashes($preload_path);
		$abspath_escaped      = addslashes(ABSPATH);

		$content = <<<'PHP'
<?php
/**
 * OPcache Preload Test File
 *
 * This file tests the preload configuration by measuring homepage load time.
 * Generated by OPcache Preload Generator.
 *
 * @generated
 */

// Security: Only allow requests with valid test token.
$token_file = '__ABSPATH__' . '.opcache_test_token';
$expected_token = file_exists($token_file) ? trim(file_get_contents($token_file)) : '';
$provided_token = $_GET['token'] ?? '';

if (empty($expected_token) || empty($provided_token) || !hash_equals($expected_token, $provided_token)) {
	http_response_code(403);
	header('Content-Type: application/json');
	echo json_encode([
		'success' => false,
		'error' => 'Invalid or missing test token',
		'code' => 'invalid_token'
	]);
	exit;
}

// Set JSON content type.
header('Content-Type: application/json');

$result = [
	'success' => false,
	'time_ms' => 0,
	'memory_peak' => 0,
	'preload_included' => false,
	'output_valid' => false,
	'error' => null,
	'code' => null
];

try {
	// Record start state.
	$start_time = hrtime(true);
	$start_memory = memory_get_usage(true);

	// Include preload file if it exists.
	$preload_path = '__PRELOAD_PATH__';
	if (file_exists($preload_path)) {
		include_once $preload_path;
		$result['preload_included'] = true;
	}

	// Define ABSPATH if not already defined.
	if (!defined('ABSPATH')) {
		define('ABSPATH', '__ABSPATH__');
	}

	// Start output buffering.
	ob_start();

	// Suppress errors to capture them.
	$old_error_reporting = error_reporting(E_ALL);
	set_error_handler(function($errno, $errstr, $errfile, $errline) use (&$result) {
		// Only capture fatal-ish errors.
		if ($errno & (E_ERROR | E_PARSE | E_CORE_ERROR | E_COMPILE_ERROR)) {
			$result['error'] = $errstr;
			$result['code'] = 'php_error';
		}
		return false; // Let normal error handler continue.
	});

	// Include WordPress.
	$wp_load = '__ABSPATH__' . 'wp-load.php';
	if (!file_exists($wp_load)) {
		throw new Exception('wp-load.php not found');
	}

	// Set up minimal request environment.
	$_SERVER['REQUEST_URI'] = '/';
	$_SERVER['REQUEST_METHOD'] = 'GET';
	$_SERVER['HTTP_HOST'] = $_SERVER['HTTP_HOST'] ?? 'localhost';

	// We need to trick WordPress into thinking this is a normal request.
	define('WP_USE_THEMES', true);

	// Include WordPress.
	require $wp_load;

	// Get the homepage.
	// Use the main query to render the homepage.
	if (function_exists('wp')) {
		wp();
	}

	// Include template if available.
	if (function_exists('get_header')) {
		// WordPress is loaded, try to get template.
		$template = get_index_template();
		if ($template) {
			include $template;
		}
	}

	// Capture output.
	$output = ob_get_clean();
	$output_length = strlen($output);

	// Restore error handling.
	restore_error_handler();
	error_reporting($old_error_reporting);

	// Calculate timing.
	$end_time = hrtime(true);
	$duration_ns = $end_time - $start_time;
	$duration_ms = $duration_ns / 1e6;

	// Validate output looks like a homepage.
	$has_html = stripos($output, '<html') !== false || stripos($output, '<!DOCTYPE') !== false;
	$has_body = stripos($output, '<body') !== false;
	$has_head = stripos($output, '<head') !== false;
	$min_length = 1000; // Minimum reasonable homepage size.

	$output_valid = $has_html && $has_body && $has_head && $output_length >= $min_length;

	// Build result.
	$result['success'] = $output_valid && empty($result['error']);
	$result['time_ms'] = round($duration_ms, 2);
	$result['memory_peak'] = memory_get_peak_usage(true);
	$result['output_valid'] = $output_valid;
	$result['output_length'] = $output_length;
	$result['checks'] = [
		'has_html' => $has_html,
		'has_body' => $has_body,
		'has_head' => $has_head,
		'min_length' => $output_length >= $min_length
	];

	if (!$output_valid && empty($result['error'])) {
		$result['error'] = 'Output does not appear to be a valid homepage';
		$result['code'] = 'invalid_output';
	}

} catch (Throwable $e) {
	// Clean up output buffer if still open.
	while (ob_get_level() > 0) {
		ob_end_clean();
	}

	$result['success'] = false;
	$result['error'] = $e->getMessage();
	$result['code'] = 'exception';
	$result['file'] = $e->getFile();
	$result['line'] = $e->getLine();
}

echo json_encode($result, JSON_PRETTY_PRINT);
exit;
PHP;

		// Replace placeholders.
		$content = str_replace('__PRELOAD_PATH__', $preload_path_escaped, $content);
		$content = str_replace('__ABSPATH__', $abspath_escaped, $content);

		// Write the file.
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents
		$written = file_put_contents($test_path, $content);

		if (false === $written) {
			return __('Failed to write test file.', 'opcache-preload-generator');
		}

		return true;
	}

	/**
	 * Delete the test file.
	 *
	 * @return bool
	 */
	public function delete_test_file(): bool {

		$test_path = $this->get_test_file_path();

		if (file_exists($test_path)) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
			return unlink($test_path);
		}

		return true;
	}

	/**
	 * Check if test file exists.
	 *
	 * @return bool
	 */
	public function test_file_exists(): bool {

		return file_exists($this->get_test_file_path());
	}

	/**
	 * Generate a secure test token.
	 *
	 * @return string
	 */
	public function generate_test_token(): string {

		return wp_generate_password(32, false);
	}

	/**
	 * Get the test URL.
	 *
	 * @param string $token Security token.
	 * @return string
	 */
	public function get_test_url(string $token): string {

		return home_url(self::TEST_FILE_NAME . '?token=' . rawurlencode($token));
	}

	/**
	 * Run the test via HTTP request.
	 *
	 * @param string $token Security token.
	 * @return array Test results.
	 */
	public function run_test(string $token): array {

		$url = $this->get_test_url($token);

		// Set the environment variable for the token.
		// This needs to be set in the PHP-FPM or Apache environment.
		// For now, we'll pass it via GET and validate in the test file.

		$response = wp_remote_get(
			$url,
			[
				'timeout'   => 60,
				'sslverify' => false,
			]
		);

		if (is_wp_error($response)) {
			return [
				'success' => false,
				'error'   => $response->get_error_message(),
				'code'    => 'request_failed',
			];
		}

		$body = wp_remote_retrieve_body($response);
		$data = json_decode($body, true);

		if (null === $data) {
			return [
				'success' => false,
				'error'   => 'Invalid JSON response from test file',
				'code'    => 'invalid_json',
				'body'    => substr($body, 0, 500),
			];
		}

		return $data;
	}
}
